version: '3.8'
services:
  db:
    container_name: labrem-apps-teleco-db
    image: mysql:8.0.30
    environment:
      TZ: America/Buenos_Aires
      MYSQL_DATABASE:      ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER:          ${MYSQL_USER}
      MYSQL_PASSWORD:      ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    restart: always
    volumes:
      - ./database/db.sql:/docker-entrypoint-initdb.d/a.sql:ro
      - ./database/db-triggers.sql:/docker-entrypoint-initdb.d/b.sql:ro
      - ./database/db-sp-laboratorios.sql:/docker-entrypoint-initdb.d/c.sql:ro
      - ./database/db-sp-ensayos.sql:/docker-entrypoint-initdb.d/d.sql:ro
      - ${PATH_DB_VOLUME}:/var/lib/mysql
    networks:
      labrem-network:
        aliases:
          - labrem-apps-teleco-db
  server:
    depends_on:
      - db
    container_name: labrem-apps-teleco-server
    image: labrem-apps-teleco-server:${VERSION}
    build:
      context: ./server
      dockerfile: ./dockerfiles/production.Dockerfile
      no_cache: true
    environment:
      TZ:           America/Buenos_Aires
      NODE_ENV:     production
      DB_HOST:      labrem-apps-teleco-db
      DB_DIALECT:   mysql
      DB_USER:      ${MYSQL_USER}
      DB_PASS:      ${MYSQL_PASSWORD}
      DB_NAME:      ${MYSQL_DATABASE}
      DB_PORT:      3306
      URL_ARDUINO:  ${URL_ARDUINO}
    ports:
      - ${SERVER_PORT}:3000
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ${PATH_CERT}:/usr/src/server/certs/cert.pem
      - ${PATH_PRIVKEY}:/usr/src/server/certs/privkey.pem
    networks:
      labrem-network:
        aliases:
          - labrem-apps-teleco-server
networks:
  labrem-network:
    external: true
