version: '3.8'
services:
  mysqldb:
    container_name: teleco-mysqldb
    image: mysql:8.0.30
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - ../volumenes/teleco-db:/var/lib/mysql
    networks:
      - local
  server:
    depends_on:
      - mysqldb
    container_name: teleco-server
    build: ./server
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $SERVER_LOCAL_PORT:$SERVER_DOCKER_PORT
    environment:
      - DB_HOST=$DB_HOST
      - DB_DIALECT=$DB_DIALECT
      - SERVER_PORT=$SERVER_DOCKER_PORT
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
    networks:
      - local
  client:
    depends_on:
      - server
    container_name: teleco-client
    build: ./client
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $CLIENT_LOCAL_PORT:$CLIENT_DOCKER_PORT
    networks:
      - local
networks:
  local:
