version: '3.8'
services:
  server:
    container_name: labrem-apps-teleco-server
    image: labrem-apps-teleco-server:${VERSION}
    build:
      dockerfile: Dockerfile
      no_cache: true
    environment:
      TZ:           America/Buenos_Aires
      NODE_ENV:     production
      DB_DIALECT:   mysql
      DB_HOST:      ${MYSQL_HOST}
      DB_PORT:      3306
      DB_USER:      ${MYSQL_USER}
      DB_PASS:      ${MYSQL_PASSWORD}
      DB_NAME:      ${MYSQL_DATABASE}
      URL_ARDUINO:  ${URL_ARDUINO}
    ports:
      - ${SERVER_PORT}:3000
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ${PATH_CERT}:/usr/src/server/certs/cert.pem
      - ${PATH_PRIVKEY}:/usr/src/server/certs/privkey.pem
    networks:
      labrem-network:
        aliases:
          - labrem-apps-teleco-server
networks:
  labrem-network:
    external: true
